# Generated by Django 3.1.2 on 2021-07-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_auto_20210724_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(blank=True, default=0, null=True, unique=True),
        ),
    ]
