# Generated by Django 3.1.2 on 2021-07-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_auto_20210724_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
